# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NewsArticleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsArticleApp
  pod 'Moya/RxSwift', '~> 15.0.0'
  pod 'Reusable', '~> 4.1'
  pod 'Kingfisher', '~> 7.8.0'
  pod 'RxSwift', '~> 6.0'
  pod 'Alamofire', '~> 5'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyBeaver', '~> 1.8.4'
  pod 'SwiftyJSON', '~> 4.0'

end
