# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

target 'NewsArticleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsArticleApp
  pod 'Moya/RxSwift'
  pod 'Reusable'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyBeaver'
  pod 'SwiftyJSON'
end
